(function() {

'use strict';

var teamStatsTestData = {
  "id": "ad4ae08f-d808-42d5-a1e6-e9bc4e34d123",
  "name": "Bengals",
  "market": "Cincinnati",
  "season": {
    "id": "46aa2ca3-c2fc-455d-8256-1f7893a87113",
    "year": 2015,
    "type": "REG",
    "name": "REG"
  },
  "record": {
    "games_played": 16,
    "touchdowns": {
      "pass": 31,
      "rush": 18,
      "total_return": 1,
      "total": 50,
      "fumble_return": 0,
      "int_return": 1,
      "kick_return": 0,
      "punt_return": 0,
      "other": 0
    },
    "rushing": {
      "avg_yards": 3.865,
      "attempts": 467,
      "touchdowns": 18,
      "tlost": 35,
      "tlost_yards": -71,
      "yards": 1805,
      "longest": 38,
      "longest_touchdown": 38,
      "redzone_attempts": 83
    },
    "receiving": {
      "targets": 495,
      "receptions": 334,
      "avg_yards": 12.287,
      "yards": 4104,
      "touchdowns": 31,
      "yards_after_catch": 1779,
      "longest": 80,
      "longest_touchdown": 80,
      "redzone_targets": 65,
      "air_yards": 2325
    },
    "punts": {
      "attempts": 69,
      "yards": 3116,
      "net_yards": 2793,
      "blocked": 1,
      "touchbacks": 6,
      "inside_20": 22,
      "return_yards": 203,
      "avg_net_yards": 41.074,
      "avg_yards": 45.824,
      "longest": 67
    },
    "punt_returns": {
      "avg_yards": 8.14,
      "returns": 43,
      "yards": 350,
      "longest": 35,
      "touchdowns": 0,
      "longest_touchdown": 0,
      "faircatches": 12
    },
    "penalties": {
      "penalties": 111,
      "yards": 917
    },
    "passing": {
      "attempts": 505,
      "completions": 334,
      "cmp_pct": 66.139,
      "interceptions": 9,
      "sack_yards": 181,
      "rating": 104,
      "touchdowns": 31,
      "avg_yards": 7.768,
      "yards": 3923,
      "sacks": 32,
      "longest": 80,
      "longest_touchdown": 80,
      "air_yards": 2325,
      "redzone_attempts": 66,
      "gross_yards": 4104
    },
    "kickoffs": {
      "kickoffs": 89,
      "endzone": 34,
      "inside_20": 20,
      "return_yards": 1041,
      "returned": 0,
      "touchbacks": 42,
      "yards": 5786,
      "out_of_bounds": 0
    },
    "kick_returns": {
      "avg_yards": 20.588,
      "returns": 34,
      "yards": 700,
      "longest": 58,
      "touchdowns": 0,
      "longest_touchdown": 0,
      "faircatches": 0
    },
    "interceptions": {
      "interceptions": 21,
      "return_yards": 202,
      "returned": 21
    },
    "int_returns": {
      "avg_yards": 9.619,
      "returns": 21,
      "yards": 202,
      "longest": 37,
      "touchdowns": 1,
      "longest_touchdown": 19
    },
    "fumbles": {
      "fumbles": 18,
      "lost_fumbles": 8,
      "own_rec": 9,
      "own_rec_yards": -54,
      "opp_rec": 7,
      "opp_rec_yards": 46,
      "out_of_bounds": 1,
      "forced_fumbles": 10,
      "own_rec_tds": 0,
      "opp_rec_tds": 0,
      "ez_rec_tds": 0
    },
    "first_downs": {
      "pass": 191,
      "penalty": 34,
      "rush": 99,
      "total": 324
    },
    "field_goals": {
      "attempts": 28,
      "made": 23,
      "blocked": 1,
      "yards": 856,
      "avg_yards": 31.704,
      "longest": 52
    },
    "extra_points": {
      "kicks": {
        "attempts": 49,
        "blocked": 1,
        "made": 48
      },
      "conversions": {
        "pass_attempts": 0,
        "pass_successes": 0,
        "rush_attempts": 1,
        "rush_successes": 1,
        "defense_attempts": 0,
        "defense_successes": 0,
        "turnover_successes": 0
      }
    },
    "efficiency": {
      "goaltogo": {
        "attempts": 32,
        "successes": 25,
        "pct": 78.125
      },
      "redzone": {
        "attempts": 58,
        "successes": 38,
        "pct": 65.517
      },
      "thirddown": {
        "attempts": 201,
        "successes": 81,
        "pct": 40.299
      },
      "fourthdown": {
        "attempts": 12,
        "successes": 7,
        "pct": 58.333
      }
    },
    "defense": {
      "tackles": 646,
      "assists": 265,
      "combined": 911,
      "sacks": 42,
      "sack_yards": 288,
      "interceptions": 21,
      "passes_defended": 87,
      "forced_fumbles": 10,
      "fumble_recoveries": 6,
      "qb_hits": 110,
      "tloss": 71,
      "tloss_yards": 345,
      "safeties": 0,
      "sp_tackles": 61,
      "sp_assists": 38,
      "sp_forced_fumbles": 0,
      "sp_fumble_recoveries": 4,
      "sp_blocks": 2,
      "misc_tackles": 10,
      "misc_assists": 4,
      "misc_forced_fumbles": 0,
      "misc_fumble_recoveries": 6,
      "missed_tackles": 118
    }
  },
  "opponents": {
    "games_played": 16,
    "touchdowns": {
      "pass": 18,
      "rush": 8,
      "total_return": 3,
      "total": 29,
      "fumble_return": 2,
      "int_return": 1,
      "kick_return": 0,
      "punt_return": 0,
      "other": 0
    },
    "rushing": {
      "avg_yards": 4.294,
      "attempts": 344,
      "touchdowns": 8,
      "tlost": 35,
      "tlost_yards": -99,
      "yards": 1477,
      "longest": 69,
      "longest_touchdown": 69,
      "redzone_attempts": 33
    },
    "receiving": {
      "targets": 634,
      "receptions": 415,
      "avg_yards": 10.275,
      "yards": 4264,
      "touchdowns": 18,
      "yards_after_catch": 1972,
      "longest": 64,
      "longest_touchdown": 64,
      "redzone_targets": 49,
      "air_yards": 2292
    },
    "punts": {
      "attempts": 77,
      "yards": 3449,
      "net_yards": 2999,
      "blocked": 0,
      "touchbacks": 5,
      "inside_20": 25,
      "return_yards": 350,
      "avg_net_yards": 38.948,
      "avg_yards": 44.792,
      "longest": 64
    },
    "punt_returns": {
      "avg_yards": 6.344,
      "returns": 32,
      "yards": 203,
      "longest": 21,
      "touchdowns": 0,
      "longest_touchdown": 0,
      "faircatches": 15
    },
    "penalties": {
      "penalties": 116,
      "yards": 1063
    },
    "passing": {
      "attempts": 646,
      "completions": 415,
      "cmp_pct": 64.241,
      "interceptions": 21,
      "sack_yards": 288,
      "rating": 78,
      "touchdowns": 18,
      "avg_yards": 6.155,
      "yards": 3976,
      "sacks": 42,
      "longest": 64,
      "longest_touchdown": 64,
      "air_yards": 2292,
      "redzone_attempts": 49,
      "gross_yards": 4264
    },
    "misc_returns": {
      "returns": 2,
      "yards": 2,
      "touchdowns": 0,
      "longest_touchdown": 0,
      "blk_fg_touchdowns": 0,
      "blk_punt_touchdowns": 0,
      "fg_return_touchdowns": 0,
      "ez_rec_touchdowns": 0
    },
    "kickoffs": {
      "kickoffs": 68,
      "endzone": 18,
      "inside_20": 13,
      "return_yards": 700,
      "returned": 0,
      "touchbacks": 30,
      "yards": 4143,
      "out_of_bounds": 1
    },
    "kick_returns": {
      "avg_yards": 22.63,
      "returns": 46,
      "yards": 1041,
      "longest": 35,
      "touchdowns": 0,
      "longest_touchdown": 0,
      "faircatches": 0
    },
    "interceptions": {
      "interceptions": 9,
      "return_yards": 136,
      "returned": 9
    },
    "int_returns": {
      "avg_yards": 15.111,
      "returns": 9,
      "yards": 136,
      "longest": 42,
      "touchdowns": 1,
      "longest_touchdown": 23
    },
    "fumbles": {
      "fumbles": 11,
      "lost_fumbles": 7,
      "own_rec": 3,
      "own_rec_yards": 0,
      "opp_rec": 8,
      "opp_rec_yards": 65,
      "out_of_bounds": 1,
      "forced_fumbles": 7,
      "own_rec_tds": 0,
      "opp_rec_tds": 2,
      "ez_rec_tds": 0
    },
    "first_downs": {
      "pass": 202,
      "penalty": 31,
      "rush": 74,
      "total": 307
    },
    "field_goals": {
      "attempts": 31,
      "made": 26,
      "blocked": 2,
      "yards": 920,
      "avg_yards": 31.724,
      "longest": 51
    },
    "extra_points": {
      "kicks": {
        "attempts": 27,
        "blocked": 0,
        "made": 27
      },
      "conversions": {
        "pass_attempts": 2,
        "pass_successes": 0,
        "rush_attempts": 0,
        "rush_successes": 0,
        "defense_attempts": 0,
        "defense_successes": 0,
        "turnover_successes": 0
      }
    },
    "efficiency": {
      "goaltogo": {
        "attempts": 16,
        "successes": 8,
        "pct": 50
      },
      "redzone": {
        "attempts": 38,
        "successes": 18,
        "pct": 47.368
      },
      "thirddown": {
        "attempts": 218,
        "successes": 86,
        "pct": 39.45
      },
      "fourthdown": {
        "attempts": 20,
        "successes": 9,
        "pct": 45
      }
    },
    "defense": {
      "tackles": 615,
      "assists": 293,
      "combined": 908,
      "sacks": 32,
      "sack_yards": 181,
      "interceptions": 9,
      "passes_defended": 56,
      "forced_fumbles": 7,
      "fumble_recoveries": 8,
      "qb_hits": 60,
      "tloss": 65,
      "tloss_yards": 275,
      "safeties": 0,
      "sp_tackles": 69,
      "sp_assists": 21,
      "sp_forced_fumbles": 0,
      "sp_fumble_recoveries": 0,
      "sp_blocks": 3,
      "misc_tackles": 21,
      "misc_assists": 1,
      "misc_forced_fumbles": 0,
      "misc_fumble_recoveries": 3,
      "missed_tackles": 105
    }
  },
  "players": [
    {
      "name": "Derron Smith",
      "jersey": "40",
      "reference": "00-0032069",
      "id": "04917392-c076-4f86-b3f2-c20350b0efb2",
      "position": "FS",
      "games_played": 16,
      "games_started": 0,
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 4,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Darqueze Dennard",
      "jersey": "21",
      "reference": "00-0031380",
      "id": "05b308c7-13f6-4ea7-baed-4314896663cb",
      "position": "CB",
      "games_played": 10,
      "games_started": 1,
      "penalties": {
        "penalties": 1,
        "yards": 10
      },
      "int_returns": {
        "returns": 1,
        "yards": 10,
        "avg_yards": 10,
        "touchdowns": 0,
        "longest": 10,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 12,
        "assists": 4,
        "combined": 16,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 1,
        "passes_defended": 3,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 2,
        "sp_assists": 2,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 2
      }
    },
    {
      "name": "Christopher Lewis-Harris",
      "jersey": "37",
      "reference": "00-0029696",
      "id": "08b0d908-ad25-4b05-8b44-8c60eabb76a8",
      "position": "CB",
      "games_played": 7,
      "games_started": 0,
      "int_returns": {
        "returns": 0,
        "yards": -1,
        "avg_yards": 0,
        "touchdowns": 0,
        "longest": -1,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 3,
        "assists": 0,
        "combined": 3,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 1,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 1,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Paul Dawson",
      "jersey": "47",
      "reference": "00-0032167",
      "id": "0cb60b75-aa36-447c-8080-0b769b05a9a4",
      "position": "OLB",
      "games_played": 11,
      "games_started": 0,
      "penalties": {
        "penalties": 1,
        "yards": 10
      },
      "defense": {
        "tackles": 3,
        "assists": 2,
        "combined": 5,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 4,
        "sp_assists": 3,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 1
      }
    },
    {
      "name": "Tyler Eifert",
      "jersey": "85",
      "reference": "00-0030549",
      "id": "14ecf9dd-3a77-4847-8e62-407cd1182f1c",
      "position": "TE",
      "games_played": 13,
      "games_started": 12,
      "receiving": {
        "receptions": 52,
        "targets": 74,
        "yards": 615,
        "avg_yards": 11.827,
        "longest": 31,
        "touchdowns": 13,
        "longest_touchdown": 22,
        "yards_after_catch": 224,
        "redzone_targets": 15,
        "air_yards": 391
      },
      "penalties": {
        "penalties": 2,
        "yards": 10
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 1,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 1,
        "misc_assists": 1,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 1,
        "missed_tackles": 0
      }
    },
    {
      "name": "Leon Hall",
      "jersey": "29",
      "reference": "00-0025405",
      "id": "16340de5-372b-4c20-953f-07a0fe26be69",
      "position": "CB",
      "games_played": 14,
      "games_started": 4,
      "int_returns": {
        "returns": 2,
        "yards": 19,
        "avg_yards": 9.5,
        "touchdowns": 1,
        "longest": 19,
        "longest_touchdown": 19
      },
      "defense": {
        "tackles": 44,
        "assists": 11,
        "combined": 55,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 2,
        "passes_defended": 9,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 1,
        "tloss_yards": 2,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 6
      }
    },
    {
      "name": "Joshua Shaw",
      "jersey": "26",
      "reference": "00-0032168",
      "id": "1686f2b7-90e8-4d0a-89f8-415310ae2bd8",
      "position": "CB",
      "games_played": 15,
      "games_started": 1,
      "penalties": {
        "penalties": 2,
        "yards": 20
      },
      "defense": {
        "tackles": 13,
        "assists": 2,
        "combined": 15,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 4,
        "sp_assists": 4,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Mohamed Sanu",
      "jersey": "12",
      "reference": "00-0029632",
      "id": "1726a359-9444-4761-a1f2-cb35ee6fa60e",
      "position": "WR",
      "games_played": 16,
      "games_started": 4,
      "rushing": {
        "avg_yards": 7.1,
        "attempts": 10,
        "touchdowns": 2,
        "yards": 71,
        "longest": 25,
        "longest_touchdown": 25,
        "redzone_attempts": 3,
        "tlost": 0,
        "tlost_yards": 0
      },
      "receiving": {
        "receptions": 33,
        "targets": 49,
        "yards": 394,
        "avg_yards": 11.939,
        "longest": 52,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 203,
        "redzone_targets": 7,
        "air_yards": 191
      },
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "kick_returns": {
        "returns": 1,
        "yards": 2,
        "avg_yards": 2,
        "touchdowns": 0,
        "longest": 2,
        "faircatches": 0,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 2,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 1,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 1,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Andre Smith",
      "jersey": "71",
      "reference": "00-0026982",
      "id": "17a056be-39c0-4913-bacf-1663f3ac4a56",
      "position": "T",
      "games_played": 14,
      "games_started": 14,
      "penalties": {
        "penalties": 10,
        "yards": 80
      }
    },
    {
      "name": "Margus Hunt",
      "jersey": "99",
      "reference": "00-0030449",
      "id": "19269eae-f3f2-47ac-b755-843489f29f65",
      "position": "DE",
      "games_played": 7,
      "games_started": 0,
      "penalties": {
        "penalties": 1,
        "yards": 10
      },
      "defense": {
        "tackles": 1,
        "assists": 1,
        "combined": 2,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Christopher Uzomah",
      "jersey": "87",
      "reference": "00-0032134",
      "id": "19858900-5c8e-49a7-ab02-34ef625724ca",
      "position": "TE",
      "games_played": 5,
      "games_started": 0,
      "receiving": {
        "receptions": 1,
        "targets": 1,
        "yards": 4,
        "avg_yards": 4,
        "longest": 4,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 2,
        "redzone_targets": 0,
        "air_yards": 2
      },
      "penalties": {
        "penalties": 1,
        "yards": 10
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 1,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Marvin Jones",
      "jersey": "82",
      "reference": "00-0029293",
      "id": "1a2fbc23-e6db-4d2f-a152-2c774341b7c4",
      "position": "WR",
      "games_played": 16,
      "games_started": 13,
      "rushing": {
        "avg_yards": 6.6,
        "attempts": 5,
        "touchdowns": 0,
        "yards": 33,
        "longest": 30,
        "longest_touchdown": 0,
        "redzone_attempts": 1,
        "tlost": 1,
        "tlost_yards": -8
      },
      "receiving": {
        "receptions": 65,
        "targets": 103,
        "yards": 816,
        "avg_yards": 12.554,
        "longest": 47,
        "touchdowns": 4,
        "longest_touchdown": 45,
        "yards_after_catch": 289,
        "redzone_targets": 12,
        "air_yards": 527
      },
      "penalties": {
        "penalties": 5,
        "yards": 30
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 3,
        "misc_assists": 1,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Cedric Peerman",
      "jersey": "30P",
      "reference": "00-0026932",
      "id": "1a316ec7-47cc-4cc4-b624-bbbf276da7b9",
      "position": "RB",
      "games_played": 16,
      "games_started": 0,
      "kick_returns": {
        "returns": 4,
        "yards": 44,
        "avg_yards": 11,
        "touchdowns": 0,
        "longest": 20,
        "faircatches": 0,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 1,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 2,
        "assists": 0,
        "combined": 2,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 1,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 13,
        "sp_assists": 4,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Patrick Sims",
      "jersey": "92",
      "reference": "00-0026217",
      "id": "1f20aaed-7f06-45c8-a868-bb5fee0be950",
      "position": "DT",
      "games_played": 8,
      "games_started": 0,
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "defense": {
        "tackles": 4,
        "assists": 12,
        "combined": 16,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 3,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Giovani Bernard",
      "jersey": "25",
      "reference": "00-0030456",
      "id": "24cf6148-f0af-4103-a215-e06956764953",
      "position": "RB",
      "games_played": 16,
      "games_started": 1,
      "rushing": {
        "avg_yards": 4.74,
        "attempts": 154,
        "touchdowns": 2,
        "yards": 730,
        "longest": 28,
        "longest_touchdown": 17,
        "redzone_attempts": 30,
        "tlost": 11,
        "tlost_yards": -17
      },
      "receiving": {
        "receptions": 49,
        "targets": 66,
        "yards": 472,
        "avg_yards": 9.633,
        "longest": 45,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 462,
        "redzone_targets": 3,
        "air_yards": 10
      },
      "penalties": {
        "penalties": 1,
        "yards": 10
      },
      "kick_returns": {
        "returns": 1,
        "yards": 6,
        "avg_yards": 6,
        "touchdowns": 0,
        "longest": 6,
        "faircatches": 0,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 2,
        "lost_fumbles": 0,
        "own_rec": 3,
        "own_rec_yards": 6,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 1,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 2,
        "missed_tackles": 0
      }
    },
    {
      "name": "George Iloka",
      "jersey": "43",
      "reference": "00-0029215",
      "id": "2b9494e4-953a-4aac-afe7-edd2d7be27da",
      "position": "SS",
      "games_played": 12,
      "games_started": 12,
      "penalties": {
        "penalties": 3,
        "yards": 45
      },
      "int_returns": {
        "returns": 1,
        "yards": 0,
        "avg_yards": 0,
        "touchdowns": 0,
        "longest": 0,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 35,
        "assists": 12,
        "combined": 47,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 1,
        "passes_defended": 4,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 1,
        "tloss": 2,
        "tloss_yards": 4,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 6
      }
    },
    {
      "name": "Gene Atkins",
      "jersey": "97",
      "reference": "00-0027720",
      "id": "2beaf8a8-ccf1-4500-a941-33ffc8141d60",
      "position": "DT",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 2,
        "yards": 10
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 1,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 31,
        "assists": 11,
        "combined": 42,
        "sacks": 11,
        "sack_yards": 86,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 1,
        "fumble_recoveries": 0,
        "qb_hits": 21,
        "tloss": 17,
        "tloss_yards": 88,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 5
      }
    },
    {
      "name": "Brandon Thompson",
      "jersey": "98",
      "reference": "00-0029684",
      "id": "30e0176b-7931-4864-9c06-dd72cc186195",
      "position": "DT",
      "games_played": 9,
      "games_started": 0,
      "defense": {
        "tackles": 4,
        "assists": 4,
        "combined": 8,
        "sacks": 0.5,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 2,
        "tloss": 3,
        "tloss_yards": 7,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 3
      }
    },
    {
      "name": "Brandon Tate",
      "jersey": "19",
      "reference": "00-0027057",
      "id": "3289f9ce-e1d1-40ed-9d3f-242a1712c586",
      "position": "WR",
      "games_played": 16,
      "games_started": 0,
      "receiving": {
        "receptions": 2,
        "targets": 3,
        "yards": 59,
        "avg_yards": 29.5,
        "longest": 55,
        "touchdowns": 1,
        "longest_touchdown": 55,
        "yards_after_catch": 10,
        "redzone_targets": 0,
        "air_yards": 49
      },
      "punt_returns": {
        "returns": 27,
        "yards": 171,
        "avg_yards": 6.333,
        "touchdowns": 0,
        "longest": 18,
        "faircatches": 11,
        "longest_touchdown": 0
      },
      "kick_returns": {
        "returns": 18,
        "yards": 413,
        "avg_yards": 22.944,
        "touchdowns": 0,
        "longest": 58,
        "faircatches": 0,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 1,
        "lost_fumbles": 0,
        "own_rec": 1,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 1,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Tyler Kroft",
      "jersey": "81",
      "reference": "00-0032214",
      "id": "36f54823-9d51-4180-9c91-d10281deb4bf",
      "position": "TE",
      "games_played": 16,
      "games_started": 6,
      "receiving": {
        "receptions": 11,
        "targets": 15,
        "yards": 129,
        "avg_yards": 11.727,
        "longest": 22,
        "touchdowns": 1,
        "longest_touchdown": 20,
        "yards_after_catch": 64,
        "redzone_targets": 0,
        "air_yards": 65
      },
      "penalties": {
        "penalties": 3,
        "yards": 25
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 4,
        "sp_assists": 6,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Christopher Carter",
      "jersey": "56",
      "reference": "00-0028100",
      "id": "3a906e08-bcd2-4bb9-8b8a-ca816f998689",
      "position": "OLB",
      "games_played": 13,
      "games_started": 0,
      "penalties": {
        "penalties": 1,
        "yards": 15
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 1,
        "own_rec_yards": 0,
        "opp_rec": 1,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 4,
        "assists": 2,
        "combined": 6,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 1,
        "qb_hits": 1,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 3,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 1,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 2
      }
    },
    {
      "name": "Emmanuel Lamur",
      "jersey": "59",
      "reference": "00-0029479",
      "id": "3f6b7426-8fc2-44c8-9cba-9d6234e9d43d",
      "position": "OLB",
      "games_played": 16,
      "games_started": 2,
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 1,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 1,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 20,
        "assists": 12,
        "combined": 32,
        "sacks": 0.5,
        "sack_yards": 4,
        "interceptions": 0,
        "passes_defended": 3,
        "forced_fumbles": 1,
        "fumble_recoveries": 0,
        "qb_hits": 1,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 7,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 1,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 6
      }
    },
    {
      "name": "Keith Wenning",
      "jersey": "3",
      "reference": "00-0030998",
      "id": "5881b91d-5797-49f9-b0a1-becbb7068ee7",
      "position": "QB",
      "games_played": 0,
      "games_started": 0
    },
    {
      "name": "Jeremy Hill",
      "jersey": "32",
      "reference": "00-0031301",
      "id": "59fc3367-5514-4616-a93c-06e4365b2293",
      "position": "RB",
      "games_played": 16,
      "games_started": 15,
      "rushing": {
        "avg_yards": 3.561,
        "attempts": 223,
        "touchdowns": 11,
        "yards": 794,
        "longest": 38,
        "longest_touchdown": 38,
        "redzone_attempts": 36,
        "tlost": 20,
        "tlost_yards": -38
      },
      "receiving": {
        "receptions": 15,
        "targets": 19,
        "yards": 79,
        "avg_yards": 5.267,
        "longest": 14,
        "touchdowns": 1,
        "longest_touchdown": 13,
        "yards_after_catch": 87,
        "redzone_targets": 4,
        "air_yards": -8
      },
      "penalties": {
        "penalties": 1,
        "yards": 15
      },
      "fumbles": {
        "fumbles": 3,
        "lost_fumbles": 3,
        "own_rec": 0,
        "own_rec_yards": -7,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "conversions": {
        "pass_attempts": 0,
        "pass_successes": 0,
        "rush_attempts": 1,
        "rush_successes": 1,
        "receive_attempts": 0,
        "receive_successes": 0,
        "defense_attempts": 0,
        "defense_successes": 0
      }
    },
    {
      "name": "Russell Bodine",
      "jersey": "61",
      "reference": "00-0031306",
      "id": "5b6c34e0-6b28-4c60-b31b-0aba6290c546",
      "position": "C",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 7,
        "yards": 65
      },
      "fumbles": {
        "fumbles": 2,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": -9,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      }
    },
    {
      "name": "Troy Hill",
      "jersey": "32",
      "reference": "00-0031785",
      "id": "5b9acfe7-f166-4a55-85f6-a654799b08dd",
      "position": "CB",
      "games_played": 3,
      "games_started": 0,
      "defense": {
        "tackles": 2,
        "assists": 1,
        "combined": 3,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 3,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Adam Jones",
      "jersey": "24J",
      "reference": "00-0023441",
      "id": "69d9c13c-2293-4eed-ae35-01c90dd45c1b",
      "position": "CB",
      "games_played": 14,
      "games_started": 14,
      "punt_returns": {
        "returns": 16,
        "yards": 179,
        "avg_yards": 11.188,
        "touchdowns": 0,
        "longest": 35,
        "faircatches": 1,
        "longest_touchdown": 0
      },
      "penalties": {
        "penalties": 4,
        "yards": 40
      },
      "kick_returns": {
        "returns": 10,
        "yards": 235,
        "avg_yards": 23.5,
        "touchdowns": 0,
        "longest": 49,
        "faircatches": 0,
        "longest_touchdown": 0
      },
      "int_returns": {
        "returns": 3,
        "yards": 14,
        "avg_yards": 4.667,
        "touchdowns": 0,
        "longest": 14,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 1,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 53,
        "assists": 9,
        "combined": 62,
        "sacks": 1,
        "sack_yards": 1,
        "interceptions": 3,
        "passes_defended": 12,
        "forced_fumbles": 1,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 1,
        "tloss_yards": 1,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 10
      }
    },
    {
      "name": "Domata Peko",
      "jersey": "94",
      "reference": "00-0024338",
      "id": "6a3bcfd5-a855-4173-a2aa-94e2c77c8268",
      "position": "NT",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 3,
        "yards": 34
      },
      "defense": {
        "tackles": 17,
        "assists": 18,
        "combined": 35,
        "sacks": 5,
        "sack_yards": 32,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 6,
        "tloss": 6,
        "tloss_yards": 33,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Mario Alford",
      "jersey": "15",
      "reference": "00-0031962",
      "id": "7ac67432-0811-432b-a425-e1abf1859475",
      "position": "WR",
      "games_played": 1,
      "games_started": 0,
      "receiving": {
        "receptions": 1,
        "targets": 1,
        "yards": 15,
        "avg_yards": 15,
        "longest": 15,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 5,
        "redzone_targets": 0,
        "air_yards": 10
      }
    },
    {
      "name": "Rey Maualuga",
      "jersey": "58",
      "reference": "00-0027014",
      "id": "822c1d36-9b42-4cfd-86bf-c83d0c71571c",
      "position": "MLB",
      "games_played": 15,
      "games_started": 14,
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "int_returns": {
        "returns": 1,
        "yards": 15,
        "avg_yards": 15,
        "touchdowns": 0,
        "longest": 15,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 1,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 43,
        "assists": 32,
        "combined": 75,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 1,
        "passes_defended": 3,
        "forced_fumbles": 0,
        "fumble_recoveries": 1,
        "qb_hits": 1,
        "tloss": 1,
        "tloss_yards": 1,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 20
      }
    },
    {
      "name": "Reggie Nelson",
      "jersey": "20",
      "reference": "00-0025408",
      "id": "9029830c-1394-494f-a92c-e192697913cf",
      "position": "FS",
      "games_played": 16,
      "games_started": 16,
      "int_returns": {
        "returns": 8,
        "yards": 115,
        "avg_yards": 14.375,
        "touchdowns": 0,
        "longest": 37,
        "longest_touchdown": 0
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 2,
        "opp_rec_yards": 25,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 50,
        "assists": 22,
        "combined": 72,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 8,
        "passes_defended": 14,
        "forced_fumbles": 0,
        "fumble_recoveries": 2,
        "qb_hits": 0,
        "tloss": 2,
        "tloss_yards": 3,
        "safeties": 0,
        "sp_tackles": 2,
        "sp_assists": 3,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 8
      }
    },
    {
      "name": "Eric Winston",
      "jersey": "73",
      "reference": "00-0024281",
      "id": "979f7f83-00e8-4ec8-9420-9e5a53f0b406",
      "position": "G",
      "games_played": 13,
      "games_started": 2,
      "penalties": {
        "penalties": 2,
        "yards": 15
      }
    },
    {
      "name": "Wallace Gilberry",
      "jersey": "95",
      "reference": "00-0026105",
      "id": "9e71b73a-c580-4d81-9b54-dcb7ec22a01f",
      "position": "DE",
      "games_played": 16,
      "games_started": 1,
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 1,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 16,
        "assists": 7,
        "combined": 23,
        "sacks": 2,
        "sack_yards": 4,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 1,
        "fumble_recoveries": 0,
        "qb_hits": 15,
        "tloss": 3,
        "tloss_yards": 14,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 1
      }
    },
    {
      "name": "Vontaze Burfict",
      "jersey": "55",
      "reference": "00-0028912",
      "id": "a62a2950-521e-4670-a4cf-47f6863fc0d1",
      "position": "OLB",
      "games_played": 10,
      "games_started": 10,
      "penalties": {
        "penalties": 6,
        "yards": 44
      },
      "int_returns": {
        "returns": 2,
        "yards": 16,
        "avg_yards": 8,
        "touchdowns": 0,
        "longest": 16,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 57,
        "assists": 17,
        "combined": 74,
        "sacks": 1,
        "sack_yards": 10,
        "interceptions": 2,
        "passes_defended": 5,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 4,
        "tloss": 6,
        "tloss_yards": 21,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 5
      }
    },
    {
      "name": "Clint Boling",
      "jersey": "65",
      "reference": "00-0028039",
      "id": "a877e5f6-37c5-4c7c-9f23-9e3a9f9d0d84",
      "position": "G",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 3,
        "yards": 20
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 1,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Jake Fisher",
      "jersey": "44",
      "reference": "00-0032196",
      "id": "aacd2e1d-0882-4698-87dc-f033382257a7",
      "position": "T",
      "games_played": 14,
      "games_started": 1,
      "receiving": {
        "receptions": 1,
        "targets": 5,
        "yards": 31,
        "avg_yards": 31,
        "longest": 31,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 19,
        "redzone_targets": 3,
        "air_yards": 12
      },
      "penalties": {
        "penalties": 3,
        "yards": 20
      }
    },
    {
      "name": "A.J. Hawk",
      "jersey": "50",
      "reference": "00-0024220",
      "id": "af8457a7-6cbe-4e2f-8bdf-2a34cba56f40",
      "position": "OLB",
      "games_played": 16,
      "games_started": 11,
      "defense": {
        "tackles": 16,
        "assists": 8,
        "combined": 24,
        "sacks": 1,
        "sack_yards": 8,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 1,
        "tloss": 2,
        "tloss_yards": 11,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 2
      }
    },
    {
      "name": "Cedric Ogbuehi",
      "jersey": "70",
      "reference": "00-0032233",
      "id": "b2805ba0-6faa-404d-b0b5-7c8ccce85f3a",
      "position": "T",
      "games_played": 5,
      "games_started": 0,
      "penalties": {
        "penalties": 1,
        "yards": 5
      }
    },
    {
      "name": "Kevin Zeitler",
      "jersey": "68",
      "reference": "00-0029592",
      "id": "b3e1206d-38e3-4ad3-be9e-8bf3daa62cad",
      "position": "G",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 1,
        "yards": 10
      }
    },
    {
      "name": "Marcus Hardison",
      "jersey": "91",
      "reference": "00-0032169",
      "id": "b6025ffc-496f-40e5-bd23-38469aa50cb7",
      "position": "DT",
      "games_played": 0,
      "games_started": 0
    },
    {
      "name": "William Clarke",
      "jersey": "93",
      "reference": "00-0031304",
      "id": "bbb3b4cf-0ba1-4d45-8650-9f8824d3781d",
      "position": "DE",
      "games_played": 12,
      "games_started": 0,
      "defense": {
        "tackles": 3,
        "assists": 1,
        "combined": 4,
        "sacks": 0.5,
        "sack_yards": 1.5,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 1,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Michael Burkhead",
      "jersey": "33",
      "reference": "00-0030288",
      "id": "bd8052bd-0898-430b-99c9-2529e895ae79",
      "position": "RB",
      "games_played": 16,
      "games_started": 0,
      "rushing": {
        "avg_yards": 1,
        "attempts": 4,
        "touchdowns": 0,
        "yards": 4,
        "longest": 2,
        "longest_touchdown": 0,
        "redzone_attempts": 0,
        "tlost": 1,
        "tlost_yards": -2
      },
      "receiving": {
        "receptions": 10,
        "targets": 15,
        "yards": 94,
        "avg_yards": 9.4,
        "longest": 27,
        "touchdowns": 1,
        "longest_touchdown": 5,
        "yards_after_catch": 25,
        "redzone_targets": 1,
        "air_yards": 69
      },
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "fumbles": {
        "fumbles": 1,
        "lost_fumbles": 1,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 6,
        "sp_assists": 5,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Adriel Green",
      "jersey": "18",
      "reference": "00-0027942",
      "id": "c9701373-23f6-4058-9189-8d9c085f3c49",
      "position": "WR",
      "games_played": 16,
      "games_started": 16,
      "receiving": {
        "receptions": 86,
        "targets": 132,
        "yards": 1297,
        "avg_yards": 15.081,
        "longest": 80,
        "touchdowns": 10,
        "longest_touchdown": 80,
        "yards_after_catch": 334,
        "redzone_targets": 18,
        "air_yards": 963
      },
      "penalties": {
        "penalties": 4,
        "yards": 30
      },
      "fumbles": {
        "fumbles": 1,
        "lost_fumbles": 1,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 2,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Shawn Williams",
      "jersey": "36",
      "reference": "00-0030471",
      "id": "c9e9bbc5-2aeb-4f72-9b7c-1a688fb235fb",
      "position": "SS",
      "games_played": 16,
      "games_started": 4,
      "penalties": {
        "penalties": 1,
        "yards": 15
      },
      "int_returns": {
        "returns": 2,
        "yards": 14,
        "avg_yards": 7,
        "touchdowns": 0,
        "longest": 14,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 22,
        "assists": 6,
        "combined": 28,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 2,
        "passes_defended": 5,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 2,
        "tloss_yards": 3,
        "safeties": 0,
        "sp_tackles": 3,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 6
      }
    },
    {
      "name": "Gregory Little",
      "jersey": "11",
      "reference": "00-0027997",
      "id": "cf15d191-0c05-46ea-811f-4d990a167805",
      "position": "WR",
      "games_played": 0,
      "games_started": 0
    },
    {
      "name": "Kevin Huber",
      "jersey": "10",
      "reference": "00-0027103",
      "id": "d14302ef-0224-4c92-961a-6d10452936ff",
      "position": "P",
      "games_played": 16,
      "games_started": 0,
      "punts": {
        "attempts": 68,
        "yards": 3116,
        "avg_yards": 46.507,
        "blocked": 1,
        "longest": 67,
        "touchbacks": 6,
        "inside_20": 22,
        "avg_net_yards": 41.687,
        "return_yards": 203,
        "net_yards": 2793
      },
      "penalties": {
        "penalties": 3,
        "yards": 15
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 1,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Andrew Dalton",
      "jersey": "14",
      "reference": "00-0027973",
      "id": "d2a0e5af-3850-4f16-8e40-a0b1d15c2ce1",
      "position": "QB",
      "games_played": 13,
      "games_started": 13,
      "rushing": {
        "avg_yards": 2.491,
        "attempts": 57,
        "touchdowns": 3,
        "yards": 142,
        "longest": 12,
        "longest_touchdown": 7,
        "redzone_attempts": 12,
        "tlost": 2,
        "tlost_yards": -6
      },
      "penalties": {
        "penalties": 3,
        "yards": 15
      },
      "passing": {
        "attempts": 386,
        "completions": 255,
        "cmp_pct": 66.062,
        "yards": 3250,
        "avg_yards": 8.42,
        "sacks": 20,
        "sack_yards": 118,
        "touchdowns": 25,
        "longest": 80,
        "interceptions": 7,
        "rating": 106.3,
        "longest_touchdown": 80,
        "air_yards": 1773,
        "redzone_attempts": 56,
        "gross_yards": 3250
      },
      "fumbles": {
        "fumbles": 5,
        "lost_fumbles": 2,
        "own_rec": 3,
        "own_rec_yards": -34,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 1,
        "misc_assists": 1,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 3,
        "missed_tackles": 0
      }
    },
    {
      "name": "Raymond McCarron",
      "jersey": "5",
      "reference": "00-0031288",
      "id": "d4b30988-e8c5-4689-8037-f79a0d3c2774",
      "position": "QB",
      "games_played": 7,
      "games_started": 3,
      "rushing": {
        "avg_yards": 2.214,
        "attempts": 14,
        "touchdowns": 0,
        "yards": 31,
        "longest": 16,
        "longest_touchdown": 0,
        "redzone_attempts": 1,
        "tlost": 0,
        "tlost_yards": 0
      },
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "passing": {
        "attempts": 119,
        "completions": 79,
        "cmp_pct": 66.387,
        "yards": 854,
        "avg_yards": 7.176,
        "sacks": 12,
        "sack_yards": 63,
        "touchdowns": 6,
        "longest": 66,
        "interceptions": 2,
        "rating": 97.1,
        "longest_touchdown": 66,
        "air_yards": 552,
        "redzone_attempts": 10,
        "gross_yards": 854
      },
      "fumbles": {
        "fumbles": 1,
        "lost_fumbles": 1,
        "own_rec": 0,
        "own_rec_yards": -10,
        "opp_rec": 0,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 0,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      }
    },
    {
      "name": "Clark Harris",
      "jersey": "46",
      "reference": "00-0025630",
      "id": "d7eec5c7-c401-485e-b0c8-fb0784c07b27",
      "position": "LS",
      "games_played": 16,
      "games_started": 0,
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 4,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Anthony Johnson",
      "jersey": "60",
      "reference": "00-0030126",
      "id": "dadcbaf3-cd13-43dd-8b7a-9f81db468872",
      "position": "C",
      "games_played": 12,
      "games_started": 0
    },
    {
      "name": "Mike Nugent",
      "jersey": "2",
      "reference": "00-0023482",
      "id": "e017e12b-07a7-4a35-b837-2faa9ffe3ce8",
      "position": "K",
      "games_played": 16,
      "games_started": 0,
      "kickoffs": {
        "kickoffs": 89,
        "endzone": 34,
        "inside_20": 20,
        "return_yards": 1041,
        "touchbacks": 42,
        "yards": 5786,
        "out_of_bounds": 0
      },
      "field_goals": {
        "attempts": 28,
        "made": 23,
        "blocked": 1,
        "yards": 856,
        "avg_yards": 31.704,
        "longest": 52
      },
      "extra_points": {
        "attempts": 48,
        "made": 48,
        "blocked": 1
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 1,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    },
    {
      "name": "Vincent Rey",
      "jersey": "57",
      "reference": "00-0027245",
      "id": "e232b84c-2e05-494a-98ac-69489544d16f",
      "position": "OLB",
      "games_played": 16,
      "games_started": 8,
      "penalties": {
        "penalties": 2,
        "yards": 17
      },
      "int_returns": {
        "returns": 1,
        "yards": 0,
        "avg_yards": 0,
        "touchdowns": 0,
        "longest": 0,
        "longest_touchdown": 0
      },
      "defense": {
        "tackles": 62,
        "assists": 33,
        "combined": 95,
        "sacks": 1,
        "sack_yards": 8,
        "interceptions": 1,
        "passes_defended": 5,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 2,
        "tloss": 3,
        "tloss_yards": 11,
        "safeties": 0,
        "sp_tackles": 2,
        "sp_assists": 1,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 11
      }
    },
    {
      "name": "Carlos Dunlap",
      "jersey": "96",
      "reference": "00-0027662",
      "id": "e79d8a12-4ec0-46d3-ae42-384f16deebed",
      "position": "DE",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 2,
        "yards": 19
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 1,
        "opp_rec_yards": 21,
        "out_of_bounds": 0,
        "forced_fumbles": 2,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 37,
        "assists": 18,
        "combined": 55,
        "sacks": 13.5,
        "sack_yards": 91.5,
        "interceptions": 0,
        "passes_defended": 1,
        "forced_fumbles": 2,
        "fumble_recoveries": 1,
        "qb_hits": 34,
        "tloss": 16,
        "tloss_yards": 96,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 2,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 3
      }
    },
    {
      "name": "D'Andre Kirkpatrick",
      "jersey": "27",
      "reference": "00-0029560",
      "id": "e972d67d-8302-4c64-9c1c-bc3121b90af4",
      "position": "CB",
      "games_played": 16,
      "games_started": 15,
      "penalties": {
        "penalties": 13,
        "yards": 118
      },
      "defense": {
        "tackles": 63,
        "assists": 7,
        "combined": 70,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 16,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 16
      }
    },
    {
      "name": "Michael Johnson",
      "jersey": "90",
      "reference": "00-0027044",
      "id": "f1769155-163f-40e5-b0a8-61c3ce0fbeac",
      "position": "DE",
      "games_played": 16,
      "games_started": 15,
      "penalties": {
        "penalties": 1,
        "yards": 5
      },
      "fumbles": {
        "fumbles": 0,
        "lost_fumbles": 0,
        "own_rec": 0,
        "own_rec_yards": 0,
        "opp_rec": 1,
        "opp_rec_yards": 0,
        "out_of_bounds": 0,
        "forced_fumbles": 3,
        "own_rec_tds": 0,
        "opp_rec_tds": 0,
        "ez_rec_tds": 0
      },
      "defense": {
        "tackles": 29,
        "assists": 13,
        "combined": 42,
        "sacks": 5,
        "sack_yards": 42,
        "interceptions": 0,
        "passes_defended": 2,
        "forced_fumbles": 3,
        "fumble_recoveries": 1,
        "qb_hits": 16,
        "tloss": 6,
        "tloss_yards": 50,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 0,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 5
      }
    },
    {
      "name": "Andrew Whitworth",
      "jersey": "77W",
      "reference": "00-0024270",
      "id": "f1ce3e7d-6afc-4db4-94f0-475bd63507b3",
      "position": "T",
      "games_played": 16,
      "games_started": 16,
      "penalties": {
        "penalties": 8,
        "yards": 70
      }
    },
    {
      "name": "Ryan Hewitt",
      "jersey": "89",
      "reference": "00-0030780",
      "id": "fa26e15f-2375-4acc-aaae-cf32cfe4bc3e",
      "position": "TE",
      "games_played": 15,
      "games_started": 12,
      "receiving": {
        "receptions": 8,
        "targets": 12,
        "yards": 99,
        "avg_yards": 12.375,
        "longest": 22,
        "touchdowns": 0,
        "longest_touchdown": 0,
        "yards_after_catch": 55,
        "redzone_targets": 2,
        "air_yards": 44
      },
      "penalties": {
        "penalties": 3,
        "yards": 25
      },
      "defense": {
        "tackles": 0,
        "assists": 0,
        "combined": 0,
        "sacks": 0,
        "sack_yards": 0,
        "interceptions": 0,
        "passes_defended": 0,
        "forced_fumbles": 0,
        "fumble_recoveries": 0,
        "qb_hits": 0,
        "tloss": 0,
        "tloss_yards": 0,
        "safeties": 0,
        "sp_tackles": 0,
        "sp_assists": 0,
        "sp_forced_fumbles": 0,
        "sp_fumble_recoveries": 0,
        "sp_blocks": 0,
        "misc_tackles": 2,
        "misc_assists": 0,
        "misc_forced_fumbles": 0,
        "misc_fumble_recoveries": 0,
        "missed_tackles": 0
      }
    }
  ],
  "_comment": "Generation started @ 2016-06-21 20:08:08 +0000 ended @ 2016-06-21 20:08:09 +0000"
};

/**
 * @ngdoc function
 * @name nflteamstatstwoApp.controller:TeamCtrl
 * @description
 * # TeamCtrl
 * Controller of the nflteamstatstwoApp
 */
angular.module('nflteamstatstwoApp')
  .controller('TeamCtrl', function ($scope, $routeParams, TeamStats) {
    $scope.teamid = $routeParams.teamid;
    $scope.TeamStats = TeamStats.query({teamid: $scope.teamid});
    
    //$scope.TeamStats = teamStatsTestData;  
  
  });
  
}());


  
 